secret_key = "/etc/rosenpass/my/pqsk"
public_key = "/etc/rosenpass/my/pqpk"
listen = ["[::]:9998"]
verbosity = "Verbose"

[[peers]]
public_key = "/etc/rosenpass/bob.pqpk"
endpoint = "remote-host:9998"
key_out = "/app/keys/pqc_psk"
