# server
secret_key = "/etc/rosenpass/my/pqsk"
public_key = "/etc/rosenpass/my/pqpk"
listen = ["0.0.0.0:9998"]
verbosity = "Verbose"

[[peers]]
public_key = "/etc/rosenpass/alice.pqpk"
# endpoint = "10.100.1.2:9998"
key_out = "/app/keys/pqc_psk"
